### ISSUE TITLE
Dashed line and conda environment

### ISSUE THREAD

**Issue by shelfofclub** [sebastianpulido/oh-my-zsh#1]
Cloud you update dashed line function from [af-magic](https://github.com/ohmyzsh/ohmyzsh/blob/bf303965e685489f2f1b764d5d22dc4766ca78c8/themes/af-magic.zsh-theme#L12) which is adaptive to conda env name and `$COLUMNS`? Maybe you can just use code in af-magic directly. I'm not good at shell script, so I'm not sure. :-)

related oh my zsh's commit and issue: https://github.com/ohmyzsh/ohmyzsh/commit/b721053c87b4662c65452117a8db35af0154a29d https://github.com/ohmyzsh/ohmyzsh/issues/8081

About conda and virtualenv:
They use different environment variables. So the plugin virtualenv can't deal with conda env. And the change by virtualenv can be prevented by just set `VIRTUAL_ENV_DISABLE_PROMPT=1`. However, conda need to be config in its config file. (edit config file or run `conda config --set changeps1 false` according to [conda doc 1](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#determining-your-current-environment) and [conda doc 2](https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#change-command-prompt-changeps1))
I think it is not good ask every user disable changeps1 manually. So conda and virtualenv should be processed separately. Just leave conda env name in ps1 and don't add it to right prompt with virtualenv.

**Comment by ashkan-mokarian** [comment]
What happened to this issue regarding af-magic and conda environments? updated omz does not work. any other workarounds?

**Comment by shelfofclub** [comment]
My PR is not merged. Now the style of this theme is different from when my PR created. I won't update this issue and PR. @ashkan-mokarian
